### ISSUE TITLE
Allow the user to run on a single file

### ISSUE THREAD

**Issue by lpil** [DamirSvrtan/fasterer#12]
Hello!

I work on some rather large codebases, and running the very cool `fasterer` on them results in more information than is humanly manageable. It would be nice if I could run it on a single file (the one I'm working on). i.e.

```
$ fasterer app/controllers/users_controller.rb
```

Thanks,
Louis

**Comment by jmccaffrey** [comment]
I had the same requirement, basically I wanted to try this out against an older ruby project, but I wouldn't be able to run this gem from that dir, because it is a much older version of ruby.

I forked, branched, and tried my hand at allowing a path or individual file to be passed in.
https://github.com/jmccaffrey/fasterer/tree/pass_in_dir

Allow a directory or individual file to be passed in

Confirmed these changes allow
1. no args  
  fasterer

2. a completely different directory (eg. an older ruby project)
  fastener 'path/to/ruby/1.8/project'

3. an individual file
 fastener 'my/current/bad_file.rb'

All current tests pass, but this needs more tests.
I'm commenting here just to say I also had the same interest, and I'm attempting my fix.
I'll look at the tests and then do a PR when I get some more time to try it.

You can try it out and see if it works for you if you need it asap.

 git clone git@github.com:jmccaffrey/fasterer.git
 cd fasterer
 bundle install
 # switch to my branch with the changes
 git checkout pass_in_dir
 rake build
 gem install pkg/fasterer-0.1.11.gem 
  # try it out
 fasterer 'path/to/your/stuff/'

**Comment by DamirSvrtan** [comment]
I'll try to look at this as soon as possible.

**Comment by DamirSvrtan** [comment]
This has been published in 0.3.0 - sorry for the extra long wait!

**Comment by lpil** [comment]
Hooray! :)

**Comment by benoittgt** [comment]
Does people use this with a git hook?

**Comment by DamirSvrtan** [comment]
@benoittgt - check this out: https://github.com/DamirSvrtan/fasterer/pull/19

**Comment by benoittgt** [comment]
Thanks @DamirSvrtan
